### PR TITLE
Filter MacOS .DS_Store directories

### LINKED ISSUE #49: gomod2nix will hash `.DS_Store` file into output hash
With recent refactoring `gomod2nix` runs much faster now, because it use the host go and the go pkg cache directory, but one problem is, macos create `.DS_Store` files into directory automatically, which makes the output hash computed incorrect.

### PR DESCRIPTION
**Pull request by adisbladis**
Now that we're hashing files directly from the Go sources on the host
system we need to avoid these files.

Closes #49.

### CODE REVIEW

File: builder/fetch.sh [hunk 1]
```diff
@@ -8,3 +8,5 @@ go mod download "$goPackagePath@$version"
 dir=$(go mod download --json "$goPackagePath@$version" | jq -r .Dir)
 
 cp -r $dir $out
+
+find $out -iname ".ds_store" | xargs -r rm -r
```
Comment (yihuang) [inline builder/fetch.sh:12]: it should be alright here since it downloads from network into a temporary directory.

Comment (adisbladis) [reply builder/fetch.sh:12]: I think so too, but on the off chance that some sources happen to contain a `.ds_store` I want to make sure that we don't have any difference in behaviour between the Go side of things and the Nix side of things.

Comment (yihuang) [reply builder/fetch.sh:12]: i see 👍
